version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./server:/server
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  # bert:
  #   build:
  #     context: ./bert
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5555:5555
  #     - 5556:5556
  #   environment:
  #     - NUM_WORKER=1
  #     - PATH_MODEL=/bert
  #   command: bert-serving-start -model_dir ./bert -num_worker=1
  

